# Generated by Django 3.2.16 on 2022-11-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('registered_number', models.IntegerField()),
                ('alt_number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('bill_data', models.DateField()),
                ('total_amount_pending', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('remaining_amount', models.IntegerField()),
                ('billing_address', models.CharField(max_length=200)),
                ('card_no', models.CharField(max_length=30)),
                ('ExpiryDate', models.DateField()),
                ('cvv', models.CharField(max_length=30)),
                ('agent_name', models.CharField(max_length=30)),
                ('query', models.TextField()),
            ],
        ),
    ]
